### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by s1u** [ilovecode1/pyfancy#1]
after run `demo()`, the following error came out in Python 2.7 or 3.5 on Mac El Capitan 

```
File "<stdin>", line 1, in <module>
  File "pyfancy/pyfancy.py", line 27, in <module>
    get = idleorcommandline()
  File "pyfancy/pyfancy.py", line 17, in idleorcommandline
    c = a[b - 1]
IndexError: string index out of range
```

**Comment by CosmicWebServices** [comment]
Thanks for telling me.

Did you follow the instructions here https://github.com/ilovecode1/pyfancy#quick-start?

And are you running it in the terminal?

Thanks for error log!

**Comment by CosmicWebServices** [comment]
I will close in the end of December if no reply

**Comment by CosmicWebServices** [comment]
Closing comment

**Comment by CosmicWebServices** [comment]
You could use AN older version that few not use that script that is having trouble
