### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by CosmicWebServices** [ilovecode1/pyfancy#16]
I guess we are working on this again so I guess we need to lay out how to contribute.

- Every PR must be reviewed by one other person at the least before getting merged.
- Proper tags must be used for organization + communication reasons.
- Travis must pass before merging (after I fix it).
- If you want to tackle an issue assign yourself or if you want to suggest someone else assign them.

Anything else?

Tagging @TheMonsterFromTheDeep @Joker314 @Jonathan50

**Comment by jeandrek** [comment]
Put it in CONTRIBUTING.md, also everybody but @joker314 is watching the repo

**Comment by CosmicWebServices** [comment]
https://github.com/ilovecode1/Pyfancy-2/pull/21

**Comment by skistaddy** [comment]
What about me?

**Comment by skistaddy** [comment]
I'm a contributor, correct? ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀^^^^^^^^^^^^

**Comment by CosmicWebServices** [comment]
@bjskistad Oh sorry I forgot...;P
