### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by CosmicWebServices** [ilovecode1/pyfancy#17]

**Comment by TheMonsterFromTheDeep** [comment]
In what way does pyfancy not support Python 3?

**Comment by CosmicWebServices** [comment]
I get errors when I run it in python 3... I will have to investigate further

**Comment by CosmicWebServices** [comment]
https://github.com/ilovecode1/Pyfancy-2/pull/22

**Comment by CosmicWebServices** [comment]
#27
