### ISSUE TITLE
Pyfancy rewrite?

### ISSUE THREAD

**Issue by CosmicWebServices** [ilovecode1/pyfancy#2]
A user @joker314 sugested a rewrite that instead of `pyfancy.<color>` do `<color>()`. Tell me how you guys think about this...

Note this would be Pyfancy 2.0!

**Comment by joker314** [comment]
I think the idea is really good :P (I'm jokebookservice1) because you won't have to surround it with constants, but just do 1 command, unlike 2 now.

**Comment by joker314** [comment]
It would be something like:
`def red(string, bg=0, escapeString=false): return "[31m" + bg + string + "]"`
However, you would need to escape the string from existing ANSI codes based on the final argument, and add background colours based on a number returned by pyFancy.<CONSTANT> or something. But that is what I'd expect it to look like, and I can help out if you like `:D`

**Comment by CosmicWebServices** [comment]
True there are problems:
- Some people just want one or just a couple of the colors so they can just copy and paste the codes. This may make it harder
- More you can do with this current way.

**Comment by skistaddy** [comment]
I think you should be able to define colors as a shortcut. Something like:

```
myCustomColor = '#FFFFFF'
print pyfancy.myCustomColor + 'my string' + pyfancy.end
```

**Comment by skistaddy** [comment]
btw, I have a company called @chikadi and I would be willing to partner with Comic Web Services. Website: https://chikadi.github.io

**Comment by CosmicWebServices** [comment]
1) You can do that already but without `pyfancy.`
2) Maybe we will

**Comment by joker314** [comment]
A company! COOL! AND YOU ARE A KID‽ But to attract more business, don't misspell `replies` as `replys`

**Comment by joker314** [comment]
Also, my idea is `pyfancy.<color>()` it is impossible to do it any other way. However, the client can do `from pyfancy import *` instead of `import pyfancy` to be able to omit `pyfancy.` _everywhere_

**Comment by CosmicWebServices** [comment]
1) Yes I am 15 I started it when I was 13.
2) I think that was what we were going to do

**Comment by joker314** [comment]
I thought I was talking about @bjskistad but do you have company too? Or is it a shared company? Anyway, is Scratch down?

**Comment by CosmicWebServices** [comment]
It is up now and yes I own a company that does the same thing that his does + a search engine that I made http://cosmicsearch.org

**Comment by skistaddy** [comment]
@joker314 Thanks for that. :P I really when it comes to computer typing, but when it comes to writing I'm right on the dime. Yes, it is my company, @coke11 is one of my "employees". He works on @chikadi/shellscript for free. Scratch is not down for me.

**Comment by joker314** [comment]
It is up again for me. Cool companies everybody! When I'm your age, I'll try and do the same thing!

**Comment by skistaddy** [comment]
Thanks! I could "employ" you too, if you wish. :P Just asking, how old ARE you?

**Comment by coke11** [comment]
I have a tech company but I can't really share a link because it has some personal info though :(.

**Comment by coke11** [comment]
I also may be looking for another developer for the company or an SEO person sometime.

**Comment by skistaddy** [comment]
Lol. Did you get this cause I mentioned you? Sorry. XD

**Comment by coke11** [comment]
Ya, it's 100% fine :)

**Comment by CosmicWebServices** [comment]
Well Hi

**Comment by coke11** [comment]
I'm the real one who should be sorry for braking scratch for 2 mins

**Comment by coke11** [comment]
Hi

**Comment by CosmicWebServices** [comment]
This is soooo off-topic
and what did u do @coke11

**Comment by skistaddy** [comment]
(@coke11 how'd you break scratch?)

**Comment by CosmicWebServices** [comment]
Me next I want to break scratch! :)

**Comment by coke11** [comment]
I was trying to change my location to say "Scratch Team" to see if it worked so I could do it on  fools day XD

**Comment by CosmicWebServices** [comment]
cool

**Comment by coke11** [comment]
The second I clicked change or whatever it said that the servers were down

**Comment by coke11** [comment]
It works with two characters but with 12 it brakes scratch XD

**Comment by CosmicWebServices** [comment]
cool and get back on topic please!

**Comment by skistaddy** [comment]
</offtopic>

**Comment by coke11** [comment]
Yes we better get back on topic. We can talk on my Scratch profile if you want.

**Comment by coke11** [comment]
About other things

**Comment by CosmicWebServices** [comment]
#4 is what will show the current idea of the code look. Also the indenting needs fixed

**Comment by joker314** [comment]
@bjskistad "How old are you?" check my Scratch profile, I can't answer here for a good reason. For that same reason, you cannot "employ" me unless I would be volounteering

**Comment by joker314** [comment]
@coke11 some people set their location to more than 9. I set mine to like 60 hex digits, and Scratch didn't break, so don't feel responsible.

**Comment by CosmicWebServices** [comment]
`</offtopic>`

**Comment by coke11** [comment]
@joker314 I used inspect element though

**Comment by joker314** [comment]
What is the blank comment for?

**Comment by joker314** [comment]
That is what I used to set it to hex digits too

**Comment by CosmicWebServices** [comment]
GET BACK ON TOPIC!!!!!

**Comment by joker314** [comment]
Why is everybody reacting to my question?  Oh, to get back on topic. I see. I just had 20 unread notifications here so wanted to respond to everything. Ok, so `</offtopic>`

**Comment by coke11** [comment]
Let's delete all of topic post. GO!

**Comment by joker314** [comment]
Good idea, I don't want GH to find out my actual age violating their aagreement

**Comment by coke11** [comment]
In the terms and conditions it says you have to be over a certain age or something?

**Comment by joker314** [comment]
It is an american law (but it applies to everyone because it is within the ToS so it affects me) that organisations cannot collect personal info of under 13s, of which I may or may not be (deleting in 60 secs)

**Comment by coke11** [comment]
ah, i have google, skype, and stuff and am not 13 (deleting in 30 secs)

**Comment by joker314** [comment]
Google has that in their agreement too.

**Comment by coke11** [comment]
ya

**Comment by joker314** [comment]
Ooh, minute is up.

**Comment by coke11** [comment]
XD

**Comment by joker314** [comment]
So are the 30 secs too

**Comment by coke11** [comment]
yes

**Comment by joker314** [comment]
I'll dig up where it says that stuff

**Comment by coke11** [comment]
i think we should delete post that don't have to do with our tech companies or this issue

**Comment by joker314** [comment]
OK. I've deleted all my posts except one addressed to @bjskistad so can I leave that one up? Also, an under 13 (who could be such a person?) can use Google but not Youtube: https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=active&q=minimum+age+to+have+google+account and as for GH none of us could possibly be under age but it is in their agreement A. Account Terms (1) You must be over 13

**Comment by joker314** [comment]
(Deleting that when you tell me you have read it)

**Comment by joker314** [comment]
Have you read it?

**Comment by jeandrek** [comment]
> @bjskistad "How old are you?" check my Scratch profile, I can't answer here for a good reason.

>GitHub scans this post and finds your Scratch profile
(jk)

**Comment by skistaddy** [comment]
@Jonathan50 XD

**Comment by skistaddy** [comment]
@joker314 By employ, I didn't mean actually hire. It's 100% volunteer.

**Comment by skistaddy** [comment]
@joker314 lol I'm 12 too. XD

**Comment by CosmicWebServices** [comment]
I love how this has nothing to do with the topic 👍

**Comment by coke11** [comment]
ya lets get back on topic we can talk about the other things on scratch

**Comment by skistaddy** [comment]
lol k

**Comment by CosmicWebServices** [comment]
So I will work on `<colot>()` tomorrow

**Comment by CosmicWebServices** [comment]
I think I will close this sense this is already done and move this to a new issue

**Comment by CosmicWebServices** [comment]
Talk at #6
