### ISSUE TITLE
Shorthand function names

### ISSUE THREAD

**Issue by TheMonsterFromTheDeep** [ilovecode1/pyfancy#20]
(Related: [this comment](https://github.com/ilovecode1/Pyfancy-2/issues/10#issuecomment-299600213))

I think it would be nice if there was some shorthand for `pyfancy().parse("...")` because it seems like it's a really useful function for static text, such as in a text-based game (e.g. things like `pyfancy().parse("You open your {bold,green INVENTORY}").output()`)

I'm not quite sure what a good shorthand name would be, or if we would want shorthand names for other functions too, or maybe if we would want to leave creating these functions to the user rather than the library (after all, it's not particularly hard to implement).

Thoughts?

**Comment by jeandrek** [comment]
Just `pyfancy("...")`?

**Comment by TheMonsterFromTheDeep** [comment]
That's certainly an option. It just doesn't seem as explicit as it could, which bothers me.

**Comment by TheMonsterFromTheDeep** [comment]
Unless of course we want to make parsing the default behavior, and make everything else just a helper method that could also be useful sometimes

**Comment by TheMonsterFromTheDeep** [comment]
@CosmicWebServices @joker314

**Comment by skistaddy** [comment]
I don't understand why we need to `.parse()` everything, seems to explicit. Also gives the vibe that we couldn't figure out how to do just `pyfancy()`.

**Comment by TheMonsterFromTheDeep** [comment]
@baranskistad well, originally, the parse() function didn't even exist--pyfancy simply used a set of functions as a sort of psuedo-markup. But now I think that maybe having pyfancy exist as, specifically, a library that *does* do parsing is perhaps the right choice.

So I would agree that making `pyfancy("...")` parse is the correct move. Does anybody else agree/disagree? @CosmicWebServices @Jonathan50

**Comment by CosmicWebServices** [comment]
I agree @TheMonsterFromTheDeep 
I honestly do not know how to do it though. Been a while...

**Comment by TheMonsterFromTheDeep** [comment]
*EDIT: Sorry, accidentally closed this. pushed the wrong button. Fixing...

**Comment by CosmicWebServices** [comment]
np

**Comment by skistaddy** [comment]
I agree, even though I'm not officially part of this. :P

**Comment by CosmicWebServices** [comment]
Made a fix https://github.com/ilovecode1/Pyfancy-2/pull/35 Almost done.

**Comment by CosmicWebServices** [comment]
OK, it is done now! I did not remove parse though... was not sure though.
