### ISSUE TITLE
Background colors

### ISSUE THREAD

**Issue by CosmicWebServices** [ilovecode1/pyfancy#25]
Is there any more colors available to the terminal? If there are can we add more to pyfancy?

**Comment by sacert** [comment]
You can go up to a 8 bit colour scheme but not all terminals support it so this might be iffy. You could add the possibility to check text styles such as bold, underline, etc in the following form:

\033[X;Y;Zm

Where X =  Text Style Code 
Y = Background Colour Code
Z = Text Colour Code

**Comment by CosmicWebServices** [comment]
#26
