### ISSUE TITLE
Markdown/bbcode or other markup language support

### ISSUE THREAD

**Issue by CosmicWebServices** [ilovecode1/pyfancy#37]
### What are you requesting?

It would be great if the pyfancy parsing also had basic markdown/bbcode or other markup language support. 
Related #36 

### How could this be implemented.

```python
pyfancy("#Bold").output()

pyfancy().parse("[color=red]RED![/color]")
```

**Comment by CosmicWebServices** [comment]
@jonathan50  @TheMonsterFromTheDeep @baranskistad @joker314

**Comment by skistaddy** [comment]
How would we do different size text? (_i.e. #, ##, ###, etc._)

**Comment by CosmicWebServices** [comment]
Good question... I will try to do research... but that might not be possible

**Comment by CosmicWebServices** [comment]
It is mostly OS specific... So that might not be possible

**Comment by skistaddy** [comment]
So maybe only support bold, underline, italics, code, etc?

**Comment by CosmicWebServices** [comment]
Yep 😄
