### ISSUE TITLE
Remove .parse()?

### ISSUE THREAD

**Issue by CosmicWebServices** [ilovecode1/pyfancy#39]
### What are you requesting?

We have implemented `pyfancy("stuff to parse")` should we remove `.parse()`?

**Comment by jeandrek** [comment]
Maybe, I don't object @TheMonsterFromTheDeep @baranskistad @joker314 @everyone

**Comment by skistaddy** [comment]
Maybe keep both just for backwards compatibility?

**Comment by TheMonsterFromTheDeep** [comment]
I think there's really no reason to remove it--it's much like the other functions (like .green()) - perhaps some people might find, for example, the following expression the most readable way to do something:`
```python
pyfancy()
    .parse("{bold Result} (primary): ")
    .green(result_primary)
    .parse("; {bold Result} (secondary): ")
    .green(result_secondary)
.print();
```
Although this is a somewhat contrived example.

**Comment by CosmicWebServices** [comment]
That makes sense now that I think about it...
