### ISSUE TITLE
Proper attribution?

### ISSUE THREAD

**Issue by TheMonsterFromTheDeep** [ilovecode1/pyfancy#42]
I'm not suuuper concerned about this, but the current credit, which simply points to the [contributions graph](https://github.com/ilovecode1/Pyfancy-2/graphs/contributors), puts me as one of the smallest contributors to the project, which makes me a little uncomfortable, as I have contributed most of the current codebase.

I'm not actually entirely sure how the contribution graph got to the place that it is.

Perhaps the document should also link to the graph for [my fork](https://github.com/TheMonsterFromTheDeep/pyfancy/graphs/contributors), which is where a lot of the current code comes from?

**Comment by CosmicWebServices** [comment]
Yeah I meant to do a better contributor section... Sorry about that. Gonna make a PR.
