### ISSUE TITLE
v2 Discussion

### ISSUE THREAD

**Issue by CosmicWebServices** [ilovecode1/pyfancy#6]
Let us talk here!

**Comment by joker314** [comment]
Ok. I'm currently working to make the run function flawless

**Comment by CosmicWebServices** [comment]
**Flawless** is a big statement

**Comment by joker314** [comment]
Then it will have to take a whole day

**Comment by CosmicWebServices** [comment]
OK what is wrong with it now that makes it not **flawless**

**Comment by joker314** [comment]
Untested, it had syntaxical errors like mising closing brackets. Also I am wondering..

Also, just to check, is this possible, and what would it do: `obj.red().bold().raw("Text").output()`
would that 
a) Make it red and bold
b) Make it only bold
?

**Comment by joker314** [comment]
As in, can you nest ANSI codes?

**Comment by CosmicWebServices** [comment]
I think the output would be just Text because I think raw will remove the before statement or maybe it will be bold and red

**Comment by CosmicWebServices** [comment]
Your second comment I will research

**Comment by CosmicWebServices** [comment]
Yes you can nest them

**Comment by joker314** [comment]
thx 4 da info.
I'll have to use a stack :(
But it will be fun :)

**Comment by joker314** [comment]
I will take a break now, and resume in about 61 minutes

**Comment by CosmicWebServices** [comment]
Cool thx for ur commitment

**Comment by joker314** [comment]
oops, I'm 20 mins late, oh well

**Comment by CosmicWebServices** [comment]
HOW DARE YOU! 👎

**Comment by joker314** [comment]
xD

**Comment by CosmicWebServices** [comment]
Woops I closed it on accident

**Comment by joker314** [comment]
Ignore the following if you want ,I'd like to make a plan:
- When you find a command followed by a { place the index and container in two lists. Once all text is logged, go through each index and pass the contents to the given command and append to the returned value.

Thanks, just needed a plan

**Comment by TheMonsterFromTheDeep** [comment]
I saw you guys were confused about the raw() modifier - what it does is resets _all_ text formatting.

**Comment by TheMonsterFromTheDeep** [comment]
So, are we developing in my fork for now? In that case I should probably figure out how to add you guys so you guys can modify it, because that way we can all work on any pull requests that are pending.

**Comment by CosmicWebServices** [comment]
We are developing in your fork

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep can you add issues to your fork. Thx!

**Comment by TheMonsterFromTheDeep** [comment]
^ Which issues?

**Comment by CosmicWebServices** [comment]
the thing we are talking in right now go to your settings and enable issues

**Comment by CosmicWebServices** [comment]
Speaking of issues I was trying rainbow and i got this:

```
>>> pyfancy().rainbow("Rainbow text").output()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyfancy.py", line 163, in rainbow
    [red, lightRed, yellow, green, lightBlue, blue][(i-x) % 6](self, addition[i])
NameError: global name 'red' is not defined
>>> 
```

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep ^^^

**Comment by TheMonsterFromTheDeep** [comment]
Huh. I guess I turned those off by accident?

**Comment by CosmicWebServices** [comment]
Maybe

**Comment by joker314** [comment]
Oh, presumable that isn't how it works :(
Hang on, let me try and fix that

**Comment by CosmicWebServices** [comment]
Closing this to move to @TheMonsterFromTheDeep fork
